### ISSUE TITLE
rtc.confの読み込みに失敗する

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist-Python#87]
**Describe the bug**
Windows上でrtc.confをShift_JIS以外の文字コードで保存してRTCを実行すると以下のメッセージを表示して異常終了する。

```
Traceback (most recent call last):
  File "RobotController.py", line 364, in <module>
    main()
  File "RobotController.py", line 358, in main
    mgr = OpenRTM_aist.Manager.init(sys.argv)
  File "C:\Python37\lib\site-packages\OpenRTM_aist\Manager.py", line 235, in init
    manager.initManager(argv)
  File "C:\Python37\lib\site-packages\OpenRTM_aist\Manager.py", line 1408, in initManager
    config.configure(self._config)
  File "C:\Python37\lib\site-packages\OpenRTM_aist\ManagerConfig.py", line 204, in configure
    prop.load(fd)
  File "C:\Python37\lib\site-packages\OpenRTM_aist\Properties.py", line 753, in load
    for readStr in inStream:
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
```

**To Reproduce**
1. rtc.confをUTF-8等で保存
2. 保存したrtc.confを指定してRTCを起動

**Reproducibility**
100％

**Expected behavior**
文字コードを判定するようにすると`chardet`等をインストールしなくてはならないため導入するかどうかは検討する必要がある。
まずは文字コードの問題でエラーになっても正常に終了するようする必要がある。

**Screenshots or Logs**

**Environment**
 - OS:  Windows 10
 - OpenRTM-aist 2.0
 - Python 3.7

**Additional context**

**Comment by Nobu19800** [comment]
#125 で対応済みのため閉じます。
